### ISSUE TITLE
Create new terminal session for running scripts

### ISSUE THREAD

**Issue by juni0r** [elliotjharper/vscode-npm-script-run#1]
Hey!

I love your extension, it's super practical and the quickest way to fire up a script.

It'd be great if a script would create a separate terminal session to run. Currently it will just toss an `npm run` in the active terminal session. If, for instance, I happen to have a psql session open, it'll end up there :)

It'd be lovely f it would work akin to the vscode builtin npm scripts sidebar. It opens a new terminal session and reuses it, if the previous command has finished.

**Comment by elliotjharper** [comment]
Hey thanks!

Made it for myself and my team and continue to just use it myself everyday.

I see your point.

Well, as a quick-win I've done a simple change so it now adds an extra command "Run NPM Script From /package.json (New Terminal)"

See https://github.com/elliotjharper/vscode-npm-script-run/commit/8cc6c94c394d6a5337294ed71ac8c366b4b860db

This gives you the ability to have it spawn a terminal for you without having to focus the terminal tab of vscode and click +.

I think tracking which terminal the extension spawned specifically would end up with some quite opinionated behaviour so I've done it this way to just leave the control in the hands of the user.
